The Pandas Python library has a read_excel() function that accepts a string literal <br>
consisting of the path to the excel spreadsheet, and returns a DataFrame. <br>

Supports the following file extensions read from a local file system or URL: <br>
xls, xlsx, xlsm, xlsb, odf, ods and odt

Supports an option to read a single sheet or a list of sheets. <br>

Rows can be dropped from a dataset with the drop() method if they contain <br>
unwanted data: <br>
data_frame_name.drop(index=data_frame_name.index[0], axis=0, inplace=True)

Assigning 0 to the "axis" parameter indicates that labels from rows will be dropped.

Assigning True to the "inplace" parameter will perform the operation in the <br>
original DataFrame rather than return a copy of the updated DataFrame.

Objective: <br>
Write a program that imports data from an excel spreadsheet and uses it to create a DataFrame.

In [2]:
import pandas as pd

./ means from the current.

HDI_Table.xlsx is in the same directory as this program.

In [30]:
df = pd.read_excel('./HDI_Table.xlsx')

Run the subsequent cell to analyze the original DataFrame.

n=10 is a keyword argument because the name of the parameter "n"
is included.

This simply means show the first ten rows inside the DataFrame named "df".

In [31]:
df.head(n=10)

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank
4,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
5,NaN,NaN,2021,NaN,2021,NaN,2021,a,2021,a,2021,NaN,2021,b,2020
6,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,Switzerland,0.962,NaN,83.9872,NaN,16.500299,NaN,13.85966,NaN,66933.00454,NaN,5,NaN,3
8,2,Norway,0.961,NaN,83.2339,NaN,18.1852,c,13.00363,NaN,64660.10622,NaN,6,NaN,1
9,3,Iceland,0.959,NaN,82.6782,NaN,19.163059,c,13.76717,NaN,55782.04981,NaN,11,NaN,2

To view all of the rows in DataFrame:

"display.max_rows" controls the number of rows to display.

999 is the max number of rows that will be displayed.

In [32]:
pd.set_option("display.max_rows", None)

Drop the rows containing unwanted data.

Drop the first three rows from the DataFrame.

In [33]:
# inplace=True specifies that the original DataFrame
# will have its data modified.
df.drop(df.index[:3], inplace=True)

Drop rows from the DataFrame beginning from index 198 to the end.

In [34]:
df.drop(df.index[198:], inplace=True)

Drop rows in index positions 4, 5, 6, 73, 123, and 168.

In [35]:
df.drop([4, 5, 6, 73, 123, 168], inplace=True)

Drop the columns containing unwanted data.

In [36]:
df.drop(df.columns[[0, 3, 5, 7, 9, 11, 12, 13, 14]], axis=1, inplace=True)

The reset_index(0 method is used to reset the index of <br>
a DataFrame to the default integer index (0, 1, 2, ...).

In [37]:
df.reset_index()

,index,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10
0,3,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
1,7,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
2,8,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
3,9,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
4,10,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
5,11,Australia,0.951,84.5265,21.05459,12.72682,49238.43335
6,12,Denmark,0.948,81.3753,18.7148,12.96049,60364.78595
7,13,Sweden,0.947,82.9833,19.41853,12.60972,54489.37401
8,14,Ireland,0.945,81.9976,18.945221,11.582223,76168.98443
9,15,Germany,0.942,80.6301,17.010139,14.090967,54534.21682
10,16,Netherlands,0.941,81.6873,18.693165,12.58163,55979.411
11,17,Finland,0.94,82.0381,19.051929,12.87362,49452.16672
12,18,Singapore,0.939,82.7545,16.524321,11.92488,90918.64471
13,19,Belgium,0.937,81.8787,19.604219,12.37568,52293.39977
14,20,New Zealand,0.937,82.4513,20.28389,12.94469,44057.31394
15,21,Canada,0.936,82.6565,16.396259,13.834427,46807.98619
16,22,Liechtenstein,0.935,83.2575,15.18157,12.53854,146829.7006
17,23,Luxembourg,0.93,82.6287,14.39814,13.015192,84649.47467
18,24,United Kingdom,0.929,80.7422,17.309719,13.40612,45224.76564
19,25,Japan,0.925,84.7839,15.221626,13.3661,42274.29134
20,26,Korea (Republic of),0.925,83.6978,16.52174,12.51293,44500.93187
21,27,United States,0.921,77.1982,16.280979,13.68343,64765.21509
22,28,Israel,0.919,82.255,16.05089,13.344866,41523.74319
23,29,Malta,0.918,83.7769,16.83857,12.21026,38884.45623
24,30,Slovenia,0.918,80.6904,17.654921,12.80368,39746.01987
25,31,Austria,0.916,81.5797,16.007959,12.25669,53618.67138
26,32,United Arab Emirates,0.911,78.7104,15.71769,12.69403,62573.59181
27,33,Spain,0.905,83.01,17.916901,10.6054,38353.60164
28,34,France,0.903,82.4988,15.81207,11.61006,45937.05273
29,35,Cyprus,0.896,81.2033,15.64827,12.44017,38188.42152
30,36,Italy,0.895,82.8502,16.226789,10.74011,42839.51441
31,37,Estonia,0.89,77.1436,15.92896,13.54843,38048.26372
32,38,Czechia,0.889,77.7283,16.219681,12.86931,38745.21386
33,39,Greece,0.887,80.1106,20.02879,11.40853,29002.48545
34,40,Poland,0.876,76.4572,16.027149,13.16475,33033.96081
35,41,Bahrain,0.875,78.7605,16.29756,11.04659,39497.24788
36,42,Lithuania,0.875,73.7201,16.285061,13.4981,37931.30359
37,43,Saudi Arabia,0.875,76.936,16.13549,11.31053,46111.55135
38,44,Portugal,0.866,81.0443,16.871229,9.57594,33154.53343
39,45,Latvia,0.863,73.5786,16.20253,13.25272,32803.23423
40,46,Andorra,0.858,80.3684,13.300239,10.55512,51166.62661
41,47,Croatia,0.858,77.5804,15.1121,12.191084,30132.28814
42,48,Chile,0.855,78.9435,16.7313,10.934966,24563.24486
43,49,Qatar,0.855,79.2716,12.63722,9.996011,87134.13469
44,50,San Marino,0.853,80.8786,12.26614,10.80146,52653.82534
45,51,Slovakia,0.848,74.9101,14.51304,12.91142,30690.48552
46,52,Hungary,0.846,74.5301,15.033628,12.24959,32789.01063
47,53,Argentina,0.842,75.3899,17.87487,11.147269,20925.26814
48,54,Türkiye,0.838,76.0324,18.338221,8.63314,31032.80106
49,55,Montenegro,0.832,76.3426,15.08161,12.176483,20838.80129
50,56,Kuwait,0.831,78.6729,15.324433,7.328023,52919.76137
51,57,Brunei Darussalam,0.829,74.6424,13.95178,9.18,64489.53954
52,58,Russian Federation,0.822,69.419,15.76637,12.774288,27166.30891
53,59,Romania,0.821,74.1847,14.2299,11.27512,30027.29131
54,60,Oman,0.816,72.5406,14.57349,11.65404,27054.32505
55,61,Bahamas,0.812,71.5983,12.89945,12.641924,30486.18429
56,62,Kazakhstan,0.811,69.3622,15.765,12.347562,23942.81837
57,63,Trinidad and Tobago,0.81,72.9709,14.535453,11.610624,23392.02084
58,64,Costa Rica,0.809,77.0232,16.545771,8.80406,19974.27358
59,65,Uruguay,0.809,75.4356,16.8326,8.98255,21268.88122
60,66,Belarus,0.808,72.438,15.16997,12.14358,18848.96704
61,67,Panama,0.805,76.2233,13.057879,10.54059,26956.83707
62,68,Malaysia,0.803,74.8839,13.34304,10.64506,26657.94355
63,69,Georgia,0.802,71.694,15.56852,12.82222,14664.16825
64,70,Mauritius,0.802,73.5552,15.17353,10.42791,22025.34631
65,71,Serbia,0.802,74.1923,14.40009,11.36987,19123.02747
66,72,Thailand,0.8,78.7154,15.882219,8.69712,17030.15352
67,74,Albania,0.796,76.4626,14.448,11.286455,14131.11039
68,75,Bulgaria,0.795,71.798,13.89729,11.41318,23078.95595
69,76,Grenada,0.795,74.9362,18.66202,9.032104,13483.5774
70,77,Barbados,0.79,77.5714,15.713385,9.852701,12306.341
71,78,Antigua and Barbuda,0.788,78.4968,14.184626,9.293741,16792.36595
72,79,Seychelles,0.785,71.2945,13.94161,10.28312,25830.61775
73,80,Sri Lanka,0.782,76.3991,14.139905,10.8273,12578.22055
74,81,Bosnia and Herzegovina,0.78,75.3003,13.8,10.53632,15241.91465
75,82,Saint Kitts and Nevis,0.777,71.6822,15.427692,8.662745,23358.33212
76,83,Iran (Islamic Republic of),0.774,73.8749,14.61525,10.636453,13000.7117
77,84,Ukraine,0.773,71.624,14.956569,11.13142,13255.50977
78,85,North Macedonia,0.77,73.8415,13.624432,10.22815,15917.75283
79,86,China,0.768,78.2107,14.236115,7.600118,17504.39969
80,87,Dominican Republic,0.767,72.6146,14.466558,9.306864,17989.60037
81,88,Moldova (Republic of),0.767,68.8459,14.433,11.82159,14875.33189
82,89,Palau,0.767,66.0204,15.78432,12.49143,13818.67869
83,90,Cuba,0.764,73.6829,14.44306,12.497734,7878.847482
84,91,Peru,0.762,72.3769,15.387734,9.885519,12245.89366
85,92,Armenia,0.759,72.0431,13.11676,11.3303,13157.9939
86,93,Mexico,0.758,70.2127,14.86444,9.22105,17896.29498
87,94,Brazil,0.754,72.7504,15.59906,8.128814,14369.88848
88,95,Colombia,0.752,72.8296,14.44275,8.86286,14384.35666
89,96,Saint Vincent and the Grenadines,0.751,69.6291,14.672206,10.83343,11961.08792
90,97,Maldives,0.747,79.9182,12.63561,7.322,15448.12788
91,98,Algeria,0.745,76.3767,14.626896,8.069284,10800.22546
92,99,Azerbaijan,0.745,69.3658,13.49689,10.54297,14256.74456
93,100,Tonga,0.745,70.9857,16.048571,11.392594,6822.03125
94,101,Turkmenistan,0.745,69.2644,13.2104,11.26139,13020.7155
95,102,Ecuador,0.74,73.67,14.62423,8.81712,10311.63273
96,103,Mongolia,0.739,70.9754,14.98035,9.4237,10588.22532
97,104,Egypt,0.731,70.2207,13.7865,9.573026,11731.69056
98,105,Tunisia,0.731,73.7719,15.425382,7.431599,10257.54477
99,106,Fiji,0.73,67.114,14.73679,10.921548,9980.110866
100,107,Suriname,0.73,70.2743,13.035644,9.776801,12672.20033
101,108,Uzbekistan,0.727,70.8616,12.47714,11.89559,7916.785725
102,109,Dominica,0.72,72.814,13.319186,8.142186,11487.62422
103,110,Jordan,0.72,74.2563,10.64656,10.44668,9923.714974
104,111,Libya,0.718,71.9112,12.85428,7.599985,15335.712
105,112,Paraguay,0.717,70.2617,12.987991,8.86184,12349.286
106,113,"Palestine, State of",0.715,73.4727,13.35801,9.93848,6582.899416
107,114,Saint Lucia,0.715,71.1114,12.86611,8.54504,12048.30381
108,115,Guyana,0.714,65.6734,12.502722,8.617477,22464.65734
109,116,South Africa,0.713,62.341,13.64371,11.37316,12948.37325
110,117,Jamaica,0.709,70.5003,13.40492,9.154629,8834.47567
111,118,Samoa,0.707,72.7675,12.418859,11.4038,5307.953374
112,119,Gabon,0.706,65.821,12.97731,9.436,13366.93455
113,120,Lebanon,0.706,75.0472,11.28587,8.718636,9525.831467
114,121,Indonesia,0.705,67.5703,13.748894,8.55651,11466.06836
115,122,Viet Nam,0.703,73.6181,12.951932,8.37028,7867.371345
116,124,Philippines,0.699,69.2664,13.12657,8.9691,8920.428468
117,125,Botswana,0.693,61.1409,12.265138,10.34,16198.31841
118,126,Bolivia (Plurinational State of),0.692,63.6304,14.946971,9.82775,8111.190194
119,127,Kyrgyzstan,0.692,69.9774,13.1953,11.374106,4566.303831
120,128,Venezuela (Bolivarian Republic of),0.691,70.5536,12.81608,11.107277,4810.882621
121,129,Iraq,0.686,70.3779,12.087473,7.905593,9977.249073
122,130,Tajikistan,0.685,71.5942,11.653036,11.333394,4547.742427
123,131,Belize,0.683,70.4697,12.99169,8.8476,6309.099778
124,132,Morocco,0.683,74.0419,14.15191,5.916,7302.81917
125,133,El Salvador,0.675,70.7479,12.671348,7.15093,8295.665889
126,134,Nicaragua,0.667,73.8368,12.641358,7.144,5624.793595
127,135,Bhutan,0.666,71.815,13.225005,5.170262,9437.541512
128,136,Cabo Verde,0.662,74.0518,12.554614,6.287719,6230.200199
129,137,Bangladesh,0.661,72.3811,12.44198,7.37906,5472.104781
130,138,Tuvalu,0.641,64.5466,9.40443,10.573108,6351.435899
131,139,Marshall Islands,0.639,65.2688,10.23932,10.88314,4619.535393
132,140,India,0.633,67.2398,11.87462,6.655109,6589.980037
133,141,Ghana,0.632,63.7954,12.04778,8.329887,5744.504017
134,142,Micronesia (Federated States of),0.628,70.71,11.54948,7.804956,3696.173945
135,143,Guatemala,0.627,69.2368,10.56245,5.6813,8723.285317
136,144,Kiribati,0.624,67.4172,11.801993,7.984462,4062.586034
137,145,Honduras,0.621,70.1229,10.132814,7.08848,5297.955301
138,146,Sao Tome and Principe,0.618,67.5912,13.365385,6.215599,4021.350815
139,147,Namibia,0.615,59.269,11.927207,7.192013,8633.504452
140,148,Lao People's Democratic Republic,0.607,68.0608,10.13611,5.374,7699.579617
141,149,Timor-Leste,0.607,67.7369,12.616098,5.43679,4460.869435
142,150,Vanuatu,0.607,70.449,11.535315,7.064846,3085.411633
143,151,Nepal,0.602,68.4495,12.88695,5.121793,3877.315444
144,152,Eswatini (Kingdom of),0.597,57.0657,13.744346,5.596,7678.591873
145,153,Equatorial Guinea,0.596,60.5943,9.73494,5.910863,12073.95993
146,154,Cambodia,0.593,69.5835,11.46772,5.088,4078.697154
147,155,Zimbabwe,0.593,59.2531,12.110969,8.710909,3809.887158
148,156,Angola,0.586,61.6434,12.1721,5.417391,5465.617791
149,157,Myanmar,0.585,65.6716,10.909138,6.3768,3850.524234
150,158,Syrian Arab Republic,0.577,72.0627,9.16422,5.1,4191.933893
151,159,Cameroon,0.576,60.3334,13.108599,6.15131,3620.932408
152,160,Kenya,0.575,61.427,10.698558,6.652,4473.570344
153,161,Congo,0.571,63.5187,12.330815,6.166,2889.283521
154,162,Zambia,0.565,61.2234,10.92876,7.187091,3217.767739
155,163,Solomon Islands,0.564,70.3477,10.32869,5.711848,2481.511362
156,164,Comoros,0.558,63.4174,11.924324,5.078649,3142.064119
157,165,Papua New Guinea,0.558,65.3506,10.360771,4.74,4008.623573
158,166,Mauritania,0.556,64.3636,9.37616,4.918805,5075.305711
159,167,Côte d'Ivoire,0.55,58.5983,10.67558,5.199139,5217.448516
160,169,Tanzania (United Republic of),0.549,66.2007,9.22149,6.372899,2664.329096
161,170,Pakistan,0.544,66.0979,8.65835,4.53633,4623.70543
162,171,Togo,0.539,61.6194,12.950494,5.016807,2166.619062
163,172,Haiti,0.535,63.1924,9.7,5.554,2847.500746
164,173,Nigeria,0.535,52.676,10.127584,7.181074,4790.284425
165,174,Rwanda,0.534,66.0722,11.23097,4.425292,2209.795202
166,175,Benin,0.525,59.821,10.76668,4.304786,3408.965923
167,176,Uganda,0.525,62.7048,10.14987,5.730942,2181.43651
168,177,Lesotho,0.514,53.062,12.040878,6.010185,2700.435748
169,178,Malawi,0.512,62.9044,12.678985,4.489695,1465.635064
170,179,Senegal,0.511,67.0926,8.96375,2.937938,3344.311825
171,180,Djibouti,0.509,62.3049,7.43298,4.1,5024.993944
172,181,Sudan,0.508,65.2667,7.945188,3.82,3575.19084
173,182,Madagascar,0.501,64.4853,10.134991,5.120469,1483.520983
174,183,Gambia,0.5,62.083,9.418626,4.637487,2172.207664
175,184,Ethiopia,0.498,64.9748,9.651071,3.201521,2361.069604
176,185,Eritrea,0.492,66.5358,8.064525,4.887235,1728.742667
177,186,Guinea-Bissau,0.483,59.6523,10.613063,3.583719,1908.24159
178,187,Liberia,0.481,60.7472,10.42079,5.082,1288.74235
179,188,Congo (Democratic Republic of the),0.479,59.193,9.817864,7.018697,1076.098781
180,189,Afghanistan,0.478,61.9824,10.263844,2.98507,1824.190915
181,190,Sierra Leone,0.477,60.0624,9.573391,4.576081,1621.512579
182,191,Guinea,0.465,58.8922,9.805297,2.202126,2480.887182
183,192,Yemen,0.455,63.7534,9.09871,3.2,1314.270189
184,193,Burkina Faso,0.449,59.2696,9.1421,2.114962,2117.915916
185,194,Mozambique,0.446,59.3247,10.219152,3.197642,1198.073924
186,195,Mali,0.428,58.9414,7.423038,2.31,2132.629443
187,196,Burundi,0.426,61.6627,10.722722,3.129267,731.786709
188,197,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611
189,198,Niger,0.4,61.5763,6.957112,2.116717,1239.866936
190,199,Chad,0.394,52.5254,8.035914,2.573774,1364.169417
191,200,South Sudan,0.385,54.9752,5.54251,5.72614,767.787

In [38]:
# Display all of the columns in the DataFrame.
df.columns

Index(['Table 1. Human Development Index and its components ', 'Unnamed: 2',
       'Unnamed: 4', 'Unnamed: 6', 'Unnamed: 8', 'Unnamed: 10'],
      dtype='object')

In [39]:
# Display all of the rows in the DataFrame.
df.index

Index([  3,   7,   8,   9,  10,  11,  12,  13,  14,  15,
       ...
       191, 192, 193, 194, 195, 196, 197, 198, 199, 200],
      dtype='int64', length=192)

In [93]:
# df[] = df['Gross national income (GNI) per capita'].apply(lambda x: f"{x:,.2f}")

Extract the data from the first column.

In [40]:
df['Table 1. Human Development Index and its components ']

3                                     NaN
7                             Switzerland
8                                  Norway
9                                 Iceland
10                 Hong Kong, China (SAR)
11                              Australia
12                                Denmark
13                                 Sweden
14                                Ireland
15                                Germany
16                            Netherlands
17                                Finland
18                              Singapore
19                                Belgium
20                            New Zealand
21                                 Canada
22                          Liechtenstein
23                             Luxembourg
24                         United Kingdom
25                                  Japan
26                    Korea (Republic of)
27                          United States
28                                 Israel
29                                  Malta
30                               Slovenia
31                                Austria
32                   United Arab Emirates
33                                  Spain
34                                 France
35                                 Cyprus
36                                  Italy
37                                Estonia
38                                Czechia
39                                 Greece
40                                 Poland
41                                Bahrain
42                              Lithuania
43                           Saudi Arabia
44                               Portugal
45                                 Latvia
46                                Andorra
47                                Croatia
48                                  Chile
49                                  Qatar
50                             San Marino
51                               Slovakia
52                                Hungary
53                              Argentina
54                                Türkiye
55                             Montenegro
56                                 Kuwait
57                      Brunei Darussalam
58                     Russian Federation
59                                Romania
60                                   Oman
61                                Bahamas
62                             Kazakhstan
63                    Trinidad and Tobago
64                             Costa Rica
65                                Uruguay
66                                Belarus
67                                 Panama
68                               Malaysia
69                                Georgia
70                              Mauritius
71                                 Serbia
72                               Thailand
74                                Albania
75                               Bulgaria
76                                Grenada
77                               Barbados
78                    Antigua and Barbuda
79                             Seychelles
80                              Sri Lanka
81                 Bosnia and Herzegovina
82                  Saint Kitts and Nevis
83             Iran (Islamic Republic of)
84                                Ukraine
85                        North Macedonia
86                                  China
87                     Dominican Republic
88                  Moldova (Republic of)
89                                  Palau
90                                   Cuba
91                                   Peru
92                                Armenia
93                                 Mexico
94                                 Brazil
95                               Colombia
96       Saint Vincent and the Grenadines
97                               Maldives
98                                Algeria
99                             Azerbaijan
100                                 Tonga
101                          Turkmenistan
102                               Ecuador
103                              Mongolia
104                                 Egypt
105                               Tunisia
106                                  Fiji
107                              Suriname
108                            Uzbekistan
109                              Dominica
110                                Jordan
111                                 Libya
112                              Paraguay
113                   Palestine, State of
114                           Saint Lucia
115                                Guyana
116                          South Africa
117                               Jamaica
118                                 Samoa
119                                 Gabon
120                               Lebanon
121                             Indonesia
122                              Viet Nam
124                           Philippines
125                              Botswana
126      Bolivia (Plurinational State of)
127                            Kyrgyzstan
128    Venezuela (Bolivarian Republic of)
129                                  Iraq
130                            Tajikistan
131                                Belize
132                               Morocco
133                           El Salvador
134                             Nicaragua
135                                Bhutan
136                            Cabo Verde
137                            Bangladesh
138                                Tuvalu
139                      Marshall Islands
140                                 India
141                                 Ghana
142      Micronesia (Federated States of)
143                             Guatemala
144                              Kiribati
145                              Honduras
146                 Sao Tome and Principe
147                               Namibia
148      Lao People's Democratic Republic
149                           Timor-Leste
150                               Vanuatu
151                                 Nepal
152                 Eswatini (Kingdom of)
153                     Equatorial Guinea
154                              Cambodia
155                              Zimbabwe
156                                Angola
157                               Myanmar
158                  Syrian Arab Republic
159                              Cameroon
160                                 Kenya
161                                 Congo
162                                Zambia
163                       Solomon Islands
164                               Comoros
165                      Papua New Guinea
166                            Mauritania
167                         Côte d'Ivoire
169         Tanzania (United Republic of)
170                              Pakistan
171                                  Togo
172                                 Haiti
173                               Nigeria
174                                Rwanda
175                                 Benin
176                                Uganda
177                               Lesotho
178                                Malawi
179                               Senegal
180                              Djibouti
181                                 Sudan
182                            Madagascar
183                                Gambia
184                              Ethiopia
185                               Eritrea
186                         Guinea-Bissau
187                               Liberia
188    Congo (Democratic Republic of the)
189                           Afghanistan
190                          Sierra Leone
191                                Guinea
192                                 Yemen
193                          Burkina Faso
194                            Mozambique
195                                  Mali
196                               Burundi
197              Central African Republic
198                                 Niger
199                                  Chad
200                           South Sudan
Name: Table 1. Human Development Index and its components , dtype: object

Extract the value in the first row and second column.

In [41]:
# df.iloc[row_index, column_index]
df.iloc[0, 1]

'Human Development Index (HDI) '

Construct a new DataFrame.

In [42]:
# Dictionary
# data_set = {'column_name': column_data}
data_set = {
    df.iloc[0, 0]: df['Table 1. Human Development Index and its components '],
    df.iloc[0, 1]: df['Unnamed: 2'],
    df.iloc[0, 2]: df['Unnamed: 4'],
    df.iloc[0, 3]: df['Unnamed: 6'],
    df.iloc[0, 4]: df['Unnamed: 8'],
    df.iloc[0, 5]: df['Unnamed: 10']
}

pd.DataFrame(data=data_set)

,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
3,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
7,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
8,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
9,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
10,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
11,Australia,0.951,84.5265,21.05459,12.72682,49238.43335
12,Denmark,0.948,81.3753,18.7148,12.96049,60364.78595
13,Sweden,0.947,82.9833,19.41853,12.60972,54489.37401
14,Ireland,0.945,81.9976,18.945221,11.582223,76168.98443
15,Germany,0.942,80.6301,17.010139,14.090967,54534.21682
16,Netherlands,0.941,81.6873,18.693165,12.58163,55979.411
17,Finland,0.94,82.0381,19.051929,12.87362,49452.16672
18,Singapore,0.939,82.7545,16.524321,11.92488,90918.64471
19,Belgium,0.937,81.8787,19.604219,12.37568,52293.39977
20,New Zealand,0.937,82.4513,20.28389,12.94469,44057.31394
21,Canada,0.936,82.6565,16.396259,13.834427,46807.98619
22,Liechtenstein,0.935,83.2575,15.18157,12.53854,146829.7006
23,Luxembourg,0.93,82.6287,14.39814,13.015192,84649.47467
24,United Kingdom,0.929,80.7422,17.309719,13.40612,45224.76564
25,Japan,0.925,84.7839,15.221626,13.3661,42274.29134
26,Korea (Republic of),0.925,83.6978,16.52174,12.51293,44500.93187
27,United States,0.921,77.1982,16.280979,13.68343,64765.21509
28,Israel,0.919,82.255,16.05089,13.344866,41523.74319
29,Malta,0.918,83.7769,16.83857,12.21026,38884.45623
30,Slovenia,0.918,80.6904,17.654921,12.80368,39746.01987
31,Austria,0.916,81.5797,16.007959,12.25669,53618.67138
32,United Arab Emirates,0.911,78.7104,15.71769,12.69403,62573.59181
33,Spain,0.905,83.01,17.916901,10.6054,38353.60164
34,France,0.903,82.4988,15.81207,11.61006,45937.05273
35,Cyprus,0.896,81.2033,15.64827,12.44017,38188.42152
36,Italy,0.895,82.8502,16.226789,10.74011,42839.51441
37,Estonia,0.89,77.1436,15.92896,13.54843,38048.26372
38,Czechia,0.889,77.7283,16.219681,12.86931,38745.21386
39,Greece,0.887,80.1106,20.02879,11.40853,29002.48545
40,Poland,0.876,76.4572,16.027149,13.16475,33033.96081
41,Bahrain,0.875,78.7605,16.29756,11.04659,39497.24788
42,Lithuania,0.875,73.7201,16.285061,13.4981,37931.30359
43,Saudi Arabia,0.875,76.936,16.13549,11.31053,46111.55135
44,Portugal,0.866,81.0443,16.871229,9.57594,33154.53343
45,Latvia,0.863,73.5786,16.20253,13.25272,32803.23423
46,Andorra,0.858,80.3684,13.300239,10.55512,51166.62661
47,Croatia,0.858,77.5804,15.1121,12.191084,30132.28814
48,Chile,0.855,78.9435,16.7313,10.934966,24563.24486
49,Qatar,0.855,79.2716,12.63722,9.996011,87134.13469
50,San Marino,0.853,80.8786,12.26614,10.80146,52653.82534
51,Slovakia,0.848,74.9101,14.51304,12.91142,30690.48552
52,Hungary,0.846,74.5301,15.033628,12.24959,32789.01063
53,Argentina,0.842,75.3899,17.87487,11.147269,20925.26814
54,Türkiye,0.838,76.0324,18.338221,8.63314,31032.80106
55,Montenegro,0.832,76.3426,15.08161,12.176483,20838.80129
56,Kuwait,0.831,78.6729,15.324433,7.328023,52919.76137
57,Brunei Darussalam,0.829,74.6424,13.95178,9.18,64489.53954
58,Russian Federation,0.822,69.419,15.76637,12.774288,27166.30891
59,Romania,0.821,74.1847,14.2299,11.27512,30027.29131
60,Oman,0.816,72.5406,14.57349,11.65404,27054.32505
61,Bahamas,0.812,71.5983,12.89945,12.641924,30486.18429
62,Kazakhstan,0.811,69.3622,15.765,12.347562,23942.81837
63,Trinidad and Tobago,0.81,72.9709,14.535453,11.610624,23392.02084
64,Costa Rica,0.809,77.0232,16.545771,8.80406,19974.27358
65,Uruguay,0.809,75.4356,16.8326,8.98255,21268.88122
66,Belarus,0.808,72.438,15.16997,12.14358,18848.96704
67,Panama,0.805,76.2233,13.057879,10.54059,26956.83707
68,Malaysia,0.803,74.8839,13.34304,10.64506,26657.94355
69,Georgia,0.802,71.694,15.56852,12.82222,14664.16825
70,Mauritius,0.802,73.5552,15.17353,10.42791,22025.34631
71,Serbia,0.802,74.1923,14.40009,11.36987,19123.02747
72,Thailand,0.8,78.7154,15.882219,8.69712,17030.15352
74,Albania,0.796,76.4626,14.448,11.286455,14131.11039
75,Bulgaria,0.795,71.798,13.89729,11.41318,23078.95595
76,Grenada,0.795,74.9362,18.66202,9.032104,13483.5774
77,Barbados,0.79,77.5714,15.713385,9.852701,12306.341
78,Antigua and Barbuda,0.788,78.4968,14.184626,9.293741,16792.36595
79,Seychelles,0.785,71.2945,13.94161,10.28312,25830.61775
80,Sri Lanka,0.782,76.3991,14.139905,10.8273,12578.22055
81,Bosnia and Herzegovina,0.78,75.3003,13.8,10.53632,15241.91465
82,Saint Kitts and Nevis,0.777,71.6822,15.427692,8.662745,23358.33212
83,Iran (Islamic Republic of),0.774,73.8749,14.61525,10.636453,13000.7117
84,Ukraine,0.773,71.624,14.956569,11.13142,13255.50977
85,North Macedonia,0.77,73.8415,13.624432,10.22815,15917.75283
86,China,0.768,78.2107,14.236115,7.600118,17504.39969
87,Dominican Republic,0.767,72.6146,14.466558,9.306864,17989.60037
88,Moldova (Republic of),0.767,68.8459,14.433,11.82159,14875.33189
89,Palau,0.767,66.0204,15.78432,12.49143,13818.67869
90,Cuba,0.764,73.6829,14.44306,12.497734,7878.847482
91,Peru,0.762,72.3769,15.387734,9.885519,12245.89366
92,Armenia,0.759,72.0431,13.11676,11.3303,13157.9939
93,Mexico,0.758,70.2127,14.86444,9.22105,17896.29498
94,Brazil,0.754,72.7504,15.59906,8.128814,14369.88848
95,Colombia,0.752,72.8296,14.44275,8.86286,14384.35666
96,Saint Vincent and the Grenadines,0.751,69.6291,14.672206,10.83343,11961.08792
97,Maldives,0.747,79.9182,12.63561,7.322,15448.12788
98,Algeria,0.745,76.3767,14.626896,8.069284,10800.22546
99,Azerbaijan,0.745,69.3658,13.49689,10.54297,14256.74456
100,Tonga,0.745,70.9857,16.048571,11.392594,6822.03125
101,Turkmenistan,0.745,69.2644,13.2104,11.26139,13020.7155
102,Ecuador,0.74,73.67,14.62423,8.81712,10311.63273
103,Mongolia,0.739,70.9754,14.98035,9.4237,10588.22532
104,Egypt,0.731,70.2207,13.7865,9.573026,11731.69056
105,Tunisia,0.731,73.7719,15.425382,7.431599,10257.54477
106,Fiji,0.73,67.114,14.73679,10.921548,9980.110866
107,Suriname,0.73,70.2743,13.035644,9.776801,12672.20033
108,Uzbekistan,0.727,70.8616,12.47714,11.89559,7916.785725
109,Dominica,0.72,72.814,13.319186,8.142186,11487.62422
110,Jordan,0.72,74.2563,10.64656,10.44668,9923.714974
111,Libya,0.718,71.9112,12.85428,7.599985,15335.712
112,Paraguay,0.717,70.2617,12.987991,8.86184,12349.286
113,"Palestine, State of",0.715,73.4727,13.35801,9.93848,6582.899416
114,Saint Lucia,0.715,71.1114,12.86611,8.54504,12048.30381
115,Guyana,0.714,65.6734,12.502722,8.617477,22464.65734
116,South Africa,0.713,62.341,13.64371,11.37316,12948.37325
117,Jamaica,0.709,70.5003,13.40492,9.154629,8834.47567
118,Samoa,0.707,72.7675,12.418859,11.4038,5307.953374
119,Gabon,0.706,65.821,12.97731,9.436,13366.93455
120,Lebanon,0.706,75.0472,11.28587,8.718636,9525.831467
121,Indonesia,0.705,67.5703,13.748894,8.55651,11466.06836
122,Viet Nam,0.703,73.6181,12.951932,8.37028,7867.371345
124,Philippines,0.699,69.2664,13.12657,8.9691,8920.428468
125,Botswana,0.693,61.1409,12.265138,10.34,16198.31841
126,Bolivia (Plurinational State of),0.692,63.6304,14.946971,9.82775,8111.190194
127,Kyrgyzstan,0.692,69.9774,13.1953,11.374106,4566.303831
128,Venezuela (Bolivarian Republic of),0.691,70.5536,12.81608,11.107277,4810.882621
129,Iraq,0.686,70.3779,12.087473,7.905593,9977.249073
130,Tajikistan,0.685,71.5942,11.653036,11.333394,4547.742427
131,Belize,0.683,70.4697,12.99169,8.8476,6309.099778
132,Morocco,0.683,74.0419,14.15191,5.916,7302.81917
133,El Salvador,0.675,70.7479,12.671348,7.15093,8295.665889
134,Nicaragua,0.667,73.8368,12.641358,7.144,5624.793595
135,Bhutan,0.666,71.815,13.225005,5.170262,9437.541512
136,Cabo Verde,0.662,74.0518,12.554614,6.287719,6230.200199
137,Bangladesh,0.661,72.3811,12.44198,7.37906,5472.104781
138,Tuvalu,0.641,64.5466,9.40443,10.573108,6351.435899
139,Marshall Islands,0.639,65.2688,10.23932,10.88314,4619.535393
140,India,0.633,67.2398,11.87462,6.655109,6589.980037
141,Ghana,0.632,63.7954,12.04778,8.329887,5744.504017
142,Micronesia (Federated States of),0.628,70.71,11.54948,7.804956,3696.173945
143,Guatemala,0.627,69.2368,10.56245,5.6813,8723.285317
144,Kiribati,0.624,67.4172,11.801993,7.984462,4062.586034
145,Honduras,0.621,70.1229,10.132814,7.08848,5297.955301
146,Sao Tome and Principe,0.618,67.5912,13.365385,6.215599,4021.350815
147,Namibia,0.615,59.269,11.927207,7.192013,8633.504452
148,Lao People's Democratic Republic,0.607,68.0608,10.13611,5.374,7699.579617
149,Timor-Leste,0.607,67.7369,12.616098,5.43679,4460.869435
150,Vanuatu,0.607,70.449,11.535315,7.064846,3085.411633
151,Nepal,0.602,68.4495,12.88695,5.121793,3877.315444
152,Eswatini (Kingdom of),0.597,57.0657,13.744346,5.596,7678.591873
153,Equatorial Guinea,0.596,60.5943,9.73494,5.910863,12073.95993
154,Cambodia,0.593,69.5835,11.46772,5.088,4078.697154
155,Zimbabwe,0.593,59.2531,12.110969,8.710909,3809.887158
156,Angola,0.586,61.6434,12.1721,5.417391,5465.617791
157,Myanmar,0.585,65.6716,10.909138,6.3768,3850.524234
158,Syrian Arab Republic,0.577,72.0627,9.16422,5.1,4191.933893
159,Cameroon,0.576,60.3334,13.108599,6.15131,3620.932408
160,Kenya,0.575,61.427,10.698558,6.652,4473.570344
161,Congo,0.571,63.5187,12.330815,6.166,2889.283521
162,Zambia,0.565,61.2234,10.92876,7.187091,3217.767739
163,Solomon Islands,0.564,70.3477,10.32869,5.711848,2481.511362
164,Comoros,0.558,63.4174,11.924324,5.078649,3142.064119
165,Papua New Guinea,0.558,65.3506,10.360771,4.74,4008.623573
166,Mauritania,0.556,64.3636,9.37616,4.918805,5075.305711
167,Côte d'Ivoire,0.55,58.5983,10.67558,5.199139,5217.448516
169,Tanzania (United Republic of),0.549,66.2007,9.22149,6.372899,2664.329096
170,Pakistan,0.544,66.0979,8.65835,4.53633,4623.70543
171,Togo,0.539,61.6194,12.950494,5.016807,2166.619062
172,Haiti,0.535,63.1924,9.7,5.554,2847.500746
173,Nigeria,0.535,52.676,10.127584,7.181074,4790.284425
174,Rwanda,0.534,66.0722,11.23097,4.425292,2209.795202
175,Benin,0.525,59.821,10.76668,4.304786,3408.965923
176,Uganda,0.525,62.7048,10.14987,5.730942,2181.43651
177,Lesotho,0.514,53.062,12.040878,6.010185,2700.435748
178,Malawi,0.512,62.9044,12.678985,4.489695,1465.635064
179,Senegal,0.511,67.0926,8.96375,2.937938,3344.311825
180,Djibouti,0.509,62.3049,7.43298,4.1,5024.993944
181,Sudan,0.508,65.2667,7.945188,3.82,3575.19084
182,Madagascar,0.501,64.4853,10.134991,5.120469,1483.520983
183,Gambia,0.5,62.083,9.418626,4.637487,2172.207664
184,Ethiopia,0.498,64.9748,9.651071,3.201521,2361.069604
185,Eritrea,0.492,66.5358,8.064525,4.887235,1728.742667
186,Guinea-Bissau,0.483,59.6523,10.613063,3.583719,1908.24159
187,Liberia,0.481,60.7472,10.42079,5.082,1288.74235
188,Congo (Democratic Republic of the),0.479,59.193,9.817864,7.018697,1076.098781
189,Afghanistan,0.478,61.9824,10.263844,2.98507,1824.190915
190,Sierra Leone,0.477,60.0624,9.573391,4.576081,1621.512579
191,Guinea,0.465,58.8922,9.805297,2.202126,2480.887182
192,Yemen,0.455,63.7534,9.09871,3.2,1314.270189
193,Burkina Faso,0.449,59.2696,9.1421,2.114962,2117.915916
194,Mozambique,0.446,59.3247,10.219152,3.197642,1198.073924
195,Mali,0.428,58.9414,7.423038,2.31,2132.629443
196,Burundi,0.426,61.6627,10.722722,3.129267,731.786709
197,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611
198,Niger,0.4,61.5763,6.957112,2.116717,1239.866936
199,Chad,0.394,52.5254,8.035914,2.573774,1364.169417
200,South Sudan,0.385,54.9752,5.54251,5.72614,767.787

In [43]:
df = df.drop(index=3)

In [44]:
df

,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10
7,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
8,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
9,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
10,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
11,Australia,0.951,84.5265,21.05459,12.72682,49238.43335
12,Denmark,0.948,81.3753,18.7148,12.96049,60364.78595
13,Sweden,0.947,82.9833,19.41853,12.60972,54489.37401
14,Ireland,0.945,81.9976,18.945221,11.582223,76168.98443
15,Germany,0.942,80.6301,17.010139,14.090967,54534.21682
16,Netherlands,0.941,81.6873,18.693165,12.58163,55979.411
17,Finland,0.94,82.0381,19.051929,12.87362,49452.16672
18,Singapore,0.939,82.7545,16.524321,11.92488,90918.64471
19,Belgium,0.937,81.8787,19.604219,12.37568,52293.39977
20,New Zealand,0.937,82.4513,20.28389,12.94469,44057.31394
21,Canada,0.936,82.6565,16.396259,13.834427,46807.98619
22,Liechtenstein,0.935,83.2575,15.18157,12.53854,146829.7006
23,Luxembourg,0.93,82.6287,14.39814,13.015192,84649.47467
24,United Kingdom,0.929,80.7422,17.309719,13.40612,45224.76564
25,Japan,0.925,84.7839,15.221626,13.3661,42274.29134
26,Korea (Republic of),0.925,83.6978,16.52174,12.51293,44500.93187
27,United States,0.921,77.1982,16.280979,13.68343,64765.21509
28,Israel,0.919,82.255,16.05089,13.344866,41523.74319
29,Malta,0.918,83.7769,16.83857,12.21026,38884.45623
30,Slovenia,0.918,80.6904,17.654921,12.80368,39746.01987
31,Austria,0.916,81.5797,16.007959,12.25669,53618.67138
32,United Arab Emirates,0.911,78.7104,15.71769,12.69403,62573.59181
33,Spain,0.905,83.01,17.916901,10.6054,38353.60164
34,France,0.903,82.4988,15.81207,11.61006,45937.05273
35,Cyprus,0.896,81.2033,15.64827,12.44017,38188.42152
36,Italy,0.895,82.8502,16.226789,10.74011,42839.51441
37,Estonia,0.89,77.1436,15.92896,13.54843,38048.26372
38,Czechia,0.889,77.7283,16.219681,12.86931,38745.21386
39,Greece,0.887,80.1106,20.02879,11.40853,29002.48545
40,Poland,0.876,76.4572,16.027149,13.16475,33033.96081
41,Bahrain,0.875,78.7605,16.29756,11.04659,39497.24788
42,Lithuania,0.875,73.7201,16.285061,13.4981,37931.30359
43,Saudi Arabia,0.875,76.936,16.13549,11.31053,46111.55135
44,Portugal,0.866,81.0443,16.871229,9.57594,33154.53343
45,Latvia,0.863,73.5786,16.20253,13.25272,32803.23423
46,Andorra,0.858,80.3684,13.300239,10.55512,51166.62661
47,Croatia,0.858,77.5804,15.1121,12.191084,30132.28814
48,Chile,0.855,78.9435,16.7313,10.934966,24563.24486
49,Qatar,0.855,79.2716,12.63722,9.996011,87134.13469
50,San Marino,0.853,80.8786,12.26614,10.80146,52653.82534
51,Slovakia,0.848,74.9101,14.51304,12.91142,30690.48552
52,Hungary,0.846,74.5301,15.033628,12.24959,32789.01063
53,Argentina,0.842,75.3899,17.87487,11.147269,20925.26814
54,Türkiye,0.838,76.0324,18.338221,8.63314,31032.80106
55,Montenegro,0.832,76.3426,15.08161,12.176483,20838.80129
56,Kuwait,0.831,78.6729,15.324433,7.328023,52919.76137
57,Brunei Darussalam,0.829,74.6424,13.95178,9.18,64489.53954
58,Russian Federation,0.822,69.419,15.76637,12.774288,27166.30891
59,Romania,0.821,74.1847,14.2299,11.27512,30027.29131
60,Oman,0.816,72.5406,14.57349,11.65404,27054.32505
61,Bahamas,0.812,71.5983,12.89945,12.641924,30486.18429
62,Kazakhstan,0.811,69.3622,15.765,12.347562,23942.81837
63,Trinidad and Tobago,0.81,72.9709,14.535453,11.610624,23392.02084
64,Costa Rica,0.809,77.0232,16.545771,8.80406,19974.27358
65,Uruguay,0.809,75.4356,16.8326,8.98255,21268.88122
66,Belarus,0.808,72.438,15.16997,12.14358,18848.96704
67,Panama,0.805,76.2233,13.057879,10.54059,26956.83707
68,Malaysia,0.803,74.8839,13.34304,10.64506,26657.94355
69,Georgia,0.802,71.694,15.56852,12.82222,14664.16825
70,Mauritius,0.802,73.5552,15.17353,10.42791,22025.34631
71,Serbia,0.802,74.1923,14.40009,11.36987,19123.02747
72,Thailand,0.8,78.7154,15.882219,8.69712,17030.15352
74,Albania,0.796,76.4626,14.448,11.286455,14131.11039
75,Bulgaria,0.795,71.798,13.89729,11.41318,23078.95595
76,Grenada,0.795,74.9362,18.66202,9.032104,13483.5774
77,Barbados,0.79,77.5714,15.713385,9.852701,12306.341
78,Antigua and Barbuda,0.788,78.4968,14.184626,9.293741,16792.36595
79,Seychelles,0.785,71.2945,13.94161,10.28312,25830.61775
80,Sri Lanka,0.782,76.3991,14.139905,10.8273,12578.22055
81,Bosnia and Herzegovina,0.78,75.3003,13.8,10.53632,15241.91465
82,Saint Kitts and Nevis,0.777,71.6822,15.427692,8.662745,23358.33212
83,Iran (Islamic Republic of),0.774,73.8749,14.61525,10.636453,13000.7117
84,Ukraine,0.773,71.624,14.956569,11.13142,13255.50977
85,North Macedonia,0.77,73.8415,13.624432,10.22815,15917.75283
86,China,0.768,78.2107,14.236115,7.600118,17504.39969
87,Dominican Republic,0.767,72.6146,14.466558,9.306864,17989.60037
88,Moldova (Republic of),0.767,68.8459,14.433,11.82159,14875.33189
89,Palau,0.767,66.0204,15.78432,12.49143,13818.67869
90,Cuba,0.764,73.6829,14.44306,12.497734,7878.847482
91,Peru,0.762,72.3769,15.387734,9.885519,12245.89366
92,Armenia,0.759,72.0431,13.11676,11.3303,13157.9939
93,Mexico,0.758,70.2127,14.86444,9.22105,17896.29498
94,Brazil,0.754,72.7504,15.59906,8.128814,14369.88848
95,Colombia,0.752,72.8296,14.44275,8.86286,14384.35666
96,Saint Vincent and the Grenadines,0.751,69.6291,14.672206,10.83343,11961.08792
97,Maldives,0.747,79.9182,12.63561,7.322,15448.12788
98,Algeria,0.745,76.3767,14.626896,8.069284,10800.22546
99,Azerbaijan,0.745,69.3658,13.49689,10.54297,14256.74456
100,Tonga,0.745,70.9857,16.048571,11.392594,6822.03125
101,Turkmenistan,0.745,69.2644,13.2104,11.26139,13020.7155
102,Ecuador,0.74,73.67,14.62423,8.81712,10311.63273
103,Mongolia,0.739,70.9754,14.98035,9.4237,10588.22532
104,Egypt,0.731,70.2207,13.7865,9.573026,11731.69056
105,Tunisia,0.731,73.7719,15.425382,7.431599,10257.54477
106,Fiji,0.73,67.114,14.73679,10.921548,9980.110866
107,Suriname,0.73,70.2743,13.035644,9.776801,12672.20033
108,Uzbekistan,0.727,70.8616,12.47714,11.89559,7916.785725
109,Dominica,0.72,72.814,13.319186,8.142186,11487.62422
110,Jordan,0.72,74.2563,10.64656,10.44668,9923.714974
111,Libya,0.718,71.9112,12.85428,7.599985,15335.712
112,Paraguay,0.717,70.2617,12.987991,8.86184,12349.286
113,"Palestine, State of",0.715,73.4727,13.35801,9.93848,6582.899416
114,Saint Lucia,0.715,71.1114,12.86611,8.54504,12048.30381
115,Guyana,0.714,65.6734,12.502722,8.617477,22464.65734
116,South Africa,0.713,62.341,13.64371,11.37316,12948.37325
117,Jamaica,0.709,70.5003,13.40492,9.154629,8834.47567
118,Samoa,0.707,72.7675,12.418859,11.4038,5307.953374
119,Gabon,0.706,65.821,12.97731,9.436,13366.93455
120,Lebanon,0.706,75.0472,11.28587,8.718636,9525.831467
121,Indonesia,0.705,67.5703,13.748894,8.55651,11466.06836
122,Viet Nam,0.703,73.6181,12.951932,8.37028,7867.371345
124,Philippines,0.699,69.2664,13.12657,8.9691,8920.428468
125,Botswana,0.693,61.1409,12.265138,10.34,16198.31841
126,Bolivia (Plurinational State of),0.692,63.6304,14.946971,9.82775,8111.190194
127,Kyrgyzstan,0.692,69.9774,13.1953,11.374106,4566.303831
128,Venezuela (Bolivarian Republic of),0.691,70.5536,12.81608,11.107277,4810.882621
129,Iraq,0.686,70.3779,12.087473,7.905593,9977.249073
130,Tajikistan,0.685,71.5942,11.653036,11.333394,4547.742427
131,Belize,0.683,70.4697,12.99169,8.8476,6309.099778
132,Morocco,0.683,74.0419,14.15191,5.916,7302.81917
133,El Salvador,0.675,70.7479,12.671348,7.15093,8295.665889
134,Nicaragua,0.667,73.8368,12.641358,7.144,5624.793595
135,Bhutan,0.666,71.815,13.225005,5.170262,9437.541512
136,Cabo Verde,0.662,74.0518,12.554614,6.287719,6230.200199
137,Bangladesh,0.661,72.3811,12.44198,7.37906,5472.104781
138,Tuvalu,0.641,64.5466,9.40443,10.573108,6351.435899
139,Marshall Islands,0.639,65.2688,10.23932,10.88314,4619.535393
140,India,0.633,67.2398,11.87462,6.655109,6589.980037
141,Ghana,0.632,63.7954,12.04778,8.329887,5744.504017
142,Micronesia (Federated States of),0.628,70.71,11.54948,7.804956,3696.173945
143,Guatemala,0.627,69.2368,10.56245,5.6813,8723.285317
144,Kiribati,0.624,67.4172,11.801993,7.984462,4062.586034
145,Honduras,0.621,70.1229,10.132814,7.08848,5297.955301
146,Sao Tome and Principe,0.618,67.5912,13.365385,6.215599,4021.350815
147,Namibia,0.615,59.269,11.927207,7.192013,8633.504452
148,Lao People's Democratic Republic,0.607,68.0608,10.13611,5.374,7699.579617
149,Timor-Leste,0.607,67.7369,12.616098,5.43679,4460.869435
150,Vanuatu,0.607,70.449,11.535315,7.064846,3085.411633
151,Nepal,0.602,68.4495,12.88695,5.121793,3877.315444
152,Eswatini (Kingdom of),0.597,57.0657,13.744346,5.596,7678.591873
153,Equatorial Guinea,0.596,60.5943,9.73494,5.910863,12073.95993
154,Cambodia,0.593,69.5835,11.46772,5.088,4078.697154
155,Zimbabwe,0.593,59.2531,12.110969,8.710909,3809.887158
156,Angola,0.586,61.6434,12.1721,5.417391,5465.617791
157,Myanmar,0.585,65.6716,10.909138,6.3768,3850.524234
158,Syrian Arab Republic,0.577,72.0627,9.16422,5.1,4191.933893
159,Cameroon,0.576,60.3334,13.108599,6.15131,3620.932408
160,Kenya,0.575,61.427,10.698558,6.652,4473.570344
161,Congo,0.571,63.5187,12.330815,6.166,2889.283521
162,Zambia,0.565,61.2234,10.92876,7.187091,3217.767739
163,Solomon Islands,0.564,70.3477,10.32869,5.711848,2481.511362
164,Comoros,0.558,63.4174,11.924324,5.078649,3142.064119
165,Papua New Guinea,0.558,65.3506,10.360771,4.74,4008.623573
166,Mauritania,0.556,64.3636,9.37616,4.918805,5075.305711
167,Côte d'Ivoire,0.55,58.5983,10.67558,5.199139,5217.448516
169,Tanzania (United Republic of),0.549,66.2007,9.22149,6.372899,2664.329096
170,Pakistan,0.544,66.0979,8.65835,4.53633,4623.70543
171,Togo,0.539,61.6194,12.950494,5.016807,2166.619062
172,Haiti,0.535,63.1924,9.7,5.554,2847.500746
173,Nigeria,0.535,52.676,10.127584,7.181074,4790.284425
174,Rwanda,0.534,66.0722,11.23097,4.425292,2209.795202
175,Benin,0.525,59.821,10.76668,4.304786,3408.965923
176,Uganda,0.525,62.7048,10.14987,5.730942,2181.43651
177,Lesotho,0.514,53.062,12.040878,6.010185,2700.435748
178,Malawi,0.512,62.9044,12.678985,4.489695,1465.635064
179,Senegal,0.511,67.0926,8.96375,2.937938,3344.311825
180,Djibouti,0.509,62.3049,7.43298,4.1,5024.993944
181,Sudan,0.508,65.2667,7.945188,3.82,3575.19084
182,Madagascar,0.501,64.4853,10.134991,5.120469,1483.520983
183,Gambia,0.5,62.083,9.418626,4.637487,2172.207664
184,Ethiopia,0.498,64.9748,9.651071,3.201521,2361.069604
185,Eritrea,0.492,66.5358,8.064525,4.887235,1728.742667
186,Guinea-Bissau,0.483,59.6523,10.613063,3.583719,1908.24159
187,Liberia,0.481,60.7472,10.42079,5.082,1288.74235
188,Congo (Democratic Republic of the),0.479,59.193,9.817864,7.018697,1076.098781
189,Afghanistan,0.478,61.9824,10.263844,2.98507,1824.190915
190,Sierra Leone,0.477,60.0624,9.573391,4.576081,1621.512579
191,Guinea,0.465,58.8922,9.805297,2.202126,2480.887182
192,Yemen,0.455,63.7534,9.09871,3.2,1314.270189
193,Burkina Faso,0.449,59.2696,9.1421,2.114962,2117.915916
194,Mozambique,0.446,59.3247,10.219152,3.197642,1198.073924
195,Mali,0.428,58.9414,7.423038,2.31,2132.629443
196,Burundi,0.426,61.6627,10.722722,3.129267,731.786709
197,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611
198,Niger,0.4,61.5763,6.957112,2.116717,1239.866936
199,Chad,0.394,52.5254,8.035914,2.573774,1364.169417
200,South Sudan,0.385,54.9752,5.54251,5.72614,767.787